const previewImageBase =
  'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80';

const previewImages = [
  previewImageBase,
  'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80',
];

export const previewUser = {
  _id: 'preview-user-1',
  firebaseUid: 'preview-firebase-user',
  email: 'preview@velve.app',
  displayName: 'Mila Velve',
  photoURL:
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  bio: 'Curating soft tailoring, clean cuts, and pieces with a second life.',
  emailVerified: true,
  averageRating: 4.9,
  completedTrades: 18,
  bodyScanUrl: previewImages[1],
  bodyScanCreatedAt: '2026-05-16T10:00:00.000Z',
  onboardingCompleted: true,
  stylePreferences: ['Vintage', 'Minimal', 'Street'],
  favoriteBrands: ['Mango', 'COS', 'Nike'],
  categories: ['Tops', 'Outerwear', 'Bags'],
  sizes: { clothing: 'M', shoes: '39' },
  location: { city: 'Belgrade', region: 'Serbia' },
  followersCount: 128,
  followingCount: 74,
  itemsCount: 12,
  joinedAt: '2026-03-24T12:00:00.000Z',
  responseRate: 96,
  successfulSwaps: 16,
  profileCompleteness: 92,
  closetCounts: { live: 4, drafts: 1, archive: 1 },
};

export const previewUsers = [
  previewUser,
  {
    _id: 'preview-user-2',
    displayName: 'Nora Studio',
    photoURL:
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    bio: 'Belgrade-based wardrobe edits, mostly oversized silhouettes.',
    averageRating: 4.8,
    completedTrades: 11,
    followersCount: 88,
    followingCount: 45,
    itemsCount: 7,
    location: { city: 'Belgrade', region: 'Serbia' },
    isSelf: false,
    isFollowing: true,
    joinedAt: '2026-04-03T12:00:00.000Z',
    responseRate: 91,
    successfulSwaps: 9,
    profileCompleteness: 86,
    stylePreferences: ['Luxury', 'Minimal'],
    favoriteBrands: ['Zara', 'Arket', 'COS'],
  },
];

export const previewItems = [
  {
    _id: 'preview-item-1',
    title: 'Velvet evening blazer',
    description:
      'Structured deep velvet blazer with a soft satin lapel. Best for evening swaps, gallery nights, and quiet drama.',
    category: 'Outerwear',
    brand: 'Mango',
    size: 'M',
    condition: 'like_new' as const,
    status: 'available',
    images: [previewImages[0]],
    primaryImage: previewImages[0],
    imageClean: previewImages[0],
    isDigitized: true,
    userId: previewUsers[1],
    createdAt: '2026-05-16T14:00:00.000Z',
    likesCount: 42,
    wishlistCount: 19,
    tradeRequestsCount: 6,
    isLiked: true,
    isWishlisted: false,
    listingType: 'both' as const,
    price: 46,
    tradeFor: 'Minimal knitwear, silver accessories, or wide trousers.',
  },
  {
    _id: 'preview-item-2',
    title: 'Air blue satin shirt',
    description: 'Lightweight satin shirt with a relaxed fit and editorial shine.',
    category: 'Tops',
    brand: 'COS',
    size: 'S',
    condition: 'good' as const,
    status: 'available',
    images: [previewImages[1]],
    primaryImage: previewImages[1],
    imageClean: previewImages[1],
    isDigitized: true,
    userId: previewUser,
    createdAt: '2026-05-15T09:30:00.000Z',
    likesCount: 31,
    wishlistCount: 15,
    tradeRequestsCount: 4,
    isLiked: false,
    isWishlisted: true,
    listingType: 'trade' as const,
    tradeFor: 'A sculptural bag or clean black skirt.',
  },
  {
    _id: 'preview-item-3',
    title: 'Lime accent mini bag',
    description: 'Small statement bag in an acidic lime tone.',
    category: 'Bags',
    brand: 'Zara',
    size: 'OS',
    condition: 'new' as const,
    status: 'draft',
    images: [previewImages[2]],
    primaryImage: previewImages[2],
    imageClean: null,
    isDigitized: false,
    userId: previewUser,
    createdAt: '2026-05-14T18:10:00.000Z',
    likesCount: 12,
    wishlistCount: 8,
    tradeRequestsCount: 1,
    isLiked: false,
    isWishlisted: false,
    listingType: 'sell' as const,
    price: 28,
  },
  {
    _id: 'preview-item-4',
    title: 'Clean black trouser',
    description: 'High-waisted trouser with a straight leg and soft drape.',
    category: 'Trousers',
    brand: 'Reserved',
    size: 'M',
    condition: 'fair' as const,
    status: 'archived',
    archiveStatus: 'sold',
    images: [previewImages[3]],
    primaryImage: previewImages[3],
    imageClean: previewImages[3],
    isDigitized: true,
    userId: previewUser,
    createdAt: '2026-05-12T11:45:00.000Z',
    likesCount: 18,
    wishlistCount: 6,
    tradeRequestsCount: 3,
    isLiked: false,
    isWishlisted: false,
    listingType: 'both' as const,
    price: 34,
  },
];

export const previewChats = [
  {
    _id: 'preview-chat-1',
    participants: [previewUser, previewUsers[1]],
    tradeRequestId: { _id: 'preview-trade-1', status: 'pending' },
    lastMessage: {
      _id: 'preview-message-1',
      text: 'I can trade the blazer for your satin shirt.',
      senderId: previewUsers[1],
      createdAt: '2026-05-18T12:30:00.000Z',
    },
    messageCount: 6,
    unreadCount: 2,
    updatedAt: '2026-05-18T12:30:00.000Z',
  },
];

export const previewMessages = [
  {
    _id: 'preview-message-1',
    text: 'I can trade the blazer for your satin shirt.',
    senderId: previewUsers[1],
    createdAt: '2026-05-18T12:30:00.000Z',
    status: 'sent',
  },
  {
    _id: 'preview-message-2',
    text: 'That sounds perfect. Can we keep the swap in Belgrade?',
    senderId: previewUser,
    createdAt: '2026-05-18T12:32:00.000Z',
    status: 'sent',
  },
];

export const previewTrades = [
  {
    _id: 'preview-trade-1',
    kind: 'trade',
    userRole: 'receiver',
    status: 'pending',
    bucket: 'pending',
    counterpart: previewUsers[1],
    offeredItemId: previewItems[0],
    requestedItemId: previewItems[1],
    offeredPrice: null,
    updatedAt: '2026-05-18T12:30:00.000Z',
    createdAt: '2026-05-18T12:20:00.000Z',
    canAccept: true,
    canReject: true,
    canCancel: false,
    canComplete: false,
    canRate: false,
  },
];

export const previewOutfits = [
  {
    _id: 'preview-outfit-1',
    name: 'Misty Night Out',
    vtoImageUrl: previewImages[0],
    isChainRender: true,
    chainSteps: 2,
  },
];
